// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: grpc/replication.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_grpc_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{0}
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentTerm   uint32                 `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	LogLength     uint32                 `protobuf:"varint,3,opt,name=logLength,proto3" json:"logLength,omitempty"`
	LastTerm      uint32                 `protobuf:"varint,4,opt,name=lastTerm,proto3" json:"lastTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_grpc_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{1}
}

func (x *VoteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VoteRequest) GetCurrentTerm() uint32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *VoteRequest) GetLogLength() uint32 {
	if x != nil {
		return x.LogLength
	}
	return 0
}

func (x *VoteRequest) GetLastTerm() uint32 {
	if x != nil {
		return x.LastTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentTerm   uint32                 `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	Accept        bool                   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_grpc_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{2}
}

func (x *VoteResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VoteResponse) GetCurrentTerm() uint32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *VoteResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type HeartbeatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentTerm   uint32                 `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_grpc_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatMsg) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HeartbeatMsg) GetCurrentTerm() uint32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

var File_grpc_replication_proto protoreflect.FileDescriptor

const file_grpc_replication_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/replication.proto\x12\x04grpc\"\x11\n" +
	"\x0fAcknowledgement\"y\n" +
	"\vVoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\rR\vcurrentTerm\x12\x1c\n" +
	"\tlogLength\x18\x03 \x01(\rR\tlogLength\x12\x1a\n" +
	"\blastTerm\x18\x04 \x01(\rR\blastTerm\"X\n" +
	"\fVoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\rR\vcurrentTerm\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\"@\n" +
	"\fHeartbeatMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\rR\vcurrentTerm2\xae\x01\n" +
	"\vRaftService\x120\n" +
	"\x04Vote\x12\x11.grpc.VoteRequest\x1a\x15.grpc.Acknowledgement\x125\n" +
	"\bResponse\x12\x12.grpc.VoteResponse\x1a\x15.grpc.Acknowledgement\x126\n" +
	"\tHeartbeat\x12\x12.grpc.HeartbeatMsg\x1a\x15.grpc.AcknowledgementB\x0eZ\fraft-go/grpcb\x06proto3"

var (
	file_grpc_replication_proto_rawDescOnce sync.Once
	file_grpc_replication_proto_rawDescData []byte
)

func file_grpc_replication_proto_rawDescGZIP() []byte {
	file_grpc_replication_proto_rawDescOnce.Do(func() {
		file_grpc_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_replication_proto_rawDesc), len(file_grpc_replication_proto_rawDesc)))
	})
	return file_grpc_replication_proto_rawDescData
}

var file_grpc_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_replication_proto_goTypes = []any{
	(*Acknowledgement)(nil), // 0: grpc.Acknowledgement
	(*VoteRequest)(nil),     // 1: grpc.VoteRequest
	(*VoteResponse)(nil),    // 2: grpc.VoteResponse
	(*HeartbeatMsg)(nil),    // 3: grpc.HeartbeatMsg
}
var file_grpc_replication_proto_depIdxs = []int32{
	1, // 0: grpc.RaftService.Vote:input_type -> grpc.VoteRequest
	2, // 1: grpc.RaftService.Response:input_type -> grpc.VoteResponse
	3, // 2: grpc.RaftService.Heartbeat:input_type -> grpc.HeartbeatMsg
	0, // 3: grpc.RaftService.Vote:output_type -> grpc.Acknowledgement
	0, // 4: grpc.RaftService.Response:output_type -> grpc.Acknowledgement
	0, // 5: grpc.RaftService.Heartbeat:output_type -> grpc.Acknowledgement
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_replication_proto_init() }
func file_grpc_replication_proto_init() {
	if File_grpc_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_replication_proto_rawDesc), len(file_grpc_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_replication_proto_goTypes,
		DependencyIndexes: file_grpc_replication_proto_depIdxs,
		MessageInfos:      file_grpc_replication_proto_msgTypes,
	}.Build()
	File_grpc_replication_proto = out.File
	file_grpc_replication_proto_goTypes = nil
	file_grpc_replication_proto_depIdxs = nil
}
